IOP_CFLAGS += -mno-check-zero-division
IOP_OBJS = main.o smap.o xfer.o ministack.o udpbd.o udptty.o imports.o exports.o
HAS_BDM ?= 1

ifeq ($(HAS_BDM), 0)
  IOP_CFLAGS += -DNO_BDM
endif

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.bin.make
include $(PS2SDKSRC)/Rules.make
